version: 2
jobs:
    build_docs:
      docker:
        - image: circleci/python:3.6.8-stretch
      steps:
        - checkout
        - run:
            name: Set BASH_ENV
            command: |
              echo "set -e" >> $BASH_ENV;
              echo "export DISPLAY=:99" >> $BASH_ENV;
              echo "export OPENBLAS_NUM_THREADS=4" >> $BASH_ENV;
              echo "export PATH=~/miniconda/bin:$PATH" >> $BASH_ENV;

        # Get environment.yml file to install MNE-Python
        - run:
            name: Get MNE-Python environment
            command: |
              curl -O https://raw.githubusercontent.com/mne-tools/mne-python/master/environment.yml

        # Load our data
        - restore_cache:
            keys:
              - data-cache-0-{{ checksum ".circleci/config.yml" }}

        # Load the python environment in a separate restore_cache call
        # Note: This cannot be integrated with restore_cache above, because
        # only the first matching key will be restored
        - restore_cache:
            keys:
              - pip-cache-0-{{ checksum "environment.yml" }}

        - run:
            name: Spin up Xvfb
            command: |
              /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset;

        # https://github.com/ContinuumIO/anaconda-issues/issues/9190#issuecomment-386508136
        # https://github.com/golemfactory/golem/issues/1019
        - run:
            name: Fix libgcc_s.so.1 pthread_cancel bug
            command: |
              sudo apt-get install libgl1-mesa-glx libegl1-mesa libxrandr2 libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6 qt5-default

        - run:
            name: Get Anaconda running and make MNE environment
            command: |
              wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh;
              chmod +x ~/miniconda.sh;
              ~/miniconda.sh -b -p ~/miniconda;
              export export PATH=~/miniconda/bin:$PATH;
              conda update --yes --quiet conda;
              conda env create -f environment.yml

        - run:
            name: Install datalad to conveniently pull testing datasets
            command: |
              source activate mne
              conda install -c conda-forge git-annex
              pip install --upgrade datalad
              datalad --version

        # Save Python environment with a key based on the environment.yml that
        # was downloaded from MNE-Python. If it changes, change the cache
        - save_cache:
            key: pip-cache-0-{{ checksum "environment.yml" }}
            paths:
              - ~/.cache/pip

        # Look at what we have and fail early if there is some library conflict
        - run:
            name: Check installation
            command: |
               source activate mne
               which python
               python -c "import mne; mne.sys_info()"

        # Run the scripts
        - run:
            name: Get data and run test
            command: |
               source activate mne
               make test

        # Save the outputs
        - store_artifacts:
            path: doc/_build/html/
            destination: dev
        - store_artifacts:
            path: doc/_build/html_stable/
            destination: stable

        # Store the cache
        - save_cache:
            key: data-cache-0-{{ checksum ".circleci/config.yml" }}
            paths:
              - ~/mne_data
              - ~/data


workflows:
  version: 2

  default:
    jobs:
      - build_docs
