version: 2
jobs:
    run_tests:
      docker:
        - image: circleci/python:3.6.8-stretch
      steps:
        - checkout
        - run:
            name: Set BASH_ENV
            command: |
              echo "set -e" >> $BASH_ENV;
              echo "export DISPLAY=:99" >> $BASH_ENV;
              echo "export OPENBLAS_NUM_THREADS=4" >> $BASH_ENV;
              echo "export PATH=~/miniconda/bin:$PATH" >> $BASH_ENV;

        # Load our data
        - restore_cache:
            keys:
              - data-cache-0-{{ checksum "tests/download_test_data.py" }}

        # Load the python environment in a separate restore_cache call
        # Note: This cannot be integrated with restore_cache above, because
        # only the first matching key will be restored
        - restore_cache:
            keys:
              - pip-cache-0

        - run:
            name: Get conda running
            command: |
              wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh;
              chmod +x ~/miniconda.sh;
              ~/miniconda.sh -b -p ~/miniconda;
              echo "export PATH=~/miniconda/bin:$PATH" >> $BASH_ENV;

        - run:
            name: Install dependencies in conda base environment
            command: |
              conda update -n base -c defaults conda
              pip install --upgrade mne
              pip install --upgrade mne_bids
              pip install --upgrade pybids

        - run:
            name: Install datalad to conveniently pull testing datasets
            command: |
              conda install -c conda-forge git-annex
              pip install --upgrade datalad
              git config --global user.email "user@mne.com"
              git config --global user.name "mne user"

        - run:
            name: Get testing datasets
            command: |
              make fetch

        # Store the data cache
        - save_cache:
            key: data-cache-0-{{ checksum "tests/download_test_data.py" }}
            paths:
              - ~/mne_data
              - ~/data

        # Save Python cache
        - save_cache:
            key: pip-cache-0
            paths:
              - ~/.cache/pip

        # Look at what we have and fail early if there is some library conflict
        - run:
            name: Check installation
            command: |
               which python
               git-annex version
               datalad --version
               mne_bids --version
               mne --version
               python -c "import mne; mne.sys_info()"

        # Run tests
        - run:
            name: test ds000117
            command: |
               export MNE_BIDS_STUDY_CONFIG=config_ds000117
               export BIDS_ROOT=~/data/ds000117
               make sensor


workflows:
  version: 2

  default:
    jobs:
      - run_tests
